export const db = {
  boards: [
    { id: 1, name: "General", shortName: "ge" },
    { id: 2, name: "Random", shortName: "rnd" },
  ],
  threads: [
    { id: 0, boardId: 1, title: "Null topic" },
    { id: 1, boardId: 1, title: "Welcome to the board" },
    { id: 2, boardId: 1, title: "Second topic" },
    { id: 3, boardId: 2, title: "Random topic" },
    { id: 4, boardId: 2, title: "Another random topic" },
    { id: 5, boardId: 1, title: "Third topic" },
    { id: 6, boardId: 1, title: "Fourth topic" },
    { id: 7, boardId: 2, title: "Fifth topic" },
    { id: 8, boardId: 1, title: "Sixth topic" },
    { id: 9, boardId: 2, title: "Seventh topic" },
    { id: 10, boardId: 1, title: "Eighth topic" },
    { id: 11, boardId: 2, title: "Ninth topic" },
    { id: 12, boardId: 1, title: "Tenth topic" },
    { id: 13, boardId: 2, title: "Eleventh topic" },
    { id: 14, boardId: 1, title: "Twelfth topic" },
    { id: 15, boardId: 2, title: "Thirteenth topic" },
    { id: 16, boardId: 1, title: "Fourteenth topic" },
    { id: 17, boardId: 2, title: "Fifteenth topic" },
    { id: 18, boardId: 1, title: "Sixteenth topic" },
    { id: 19, boardId: 2, title: "Seventeenth topic" },
    { id: 20, boardId: 1, title: "Eighteenth topic" },
    { id: 21, boardId: 2, title: "Nineteenth topic" },
    { id: 22, boardId: 1, title: "Twentieth topic" },
    { id: 23, boardId: 2, title: "Twenty-first topic" },
    { id: 24, boardId: 1, title: "Twenty-second topic" },
    { id: 25, boardId: 2, title: "Twenty-third topic" },
    { id: 26, boardId: 1, title: "Twenty-fourth topic" },
    { id: 27, boardId: 2, title: "Twenty-fifth topic" },
    { id: 28, boardId: 1, title: "Twenty-sixth topic" },
    { id: 29, boardId: 2, title: "Twenty-seventh topic" },
    { id: 30, boardId: 1, title: "Twenty-eighth topic" },
    { id: 31, boardId: 2, title: "Twenty-ninth topic" },
    { id: 32, boardId: 1, title: "Thirtieth topic" },
    { id: 33, boardId: 2, title: "Thirty-first topic" },
    { id: 34, boardId: 1, title: "Thirty-second topic" },
    { id: 35, boardId: 2, title: "Thirty-third topic" },
    { id: 36, boardId: 1, title: "Thirty-fourth topic" },
    { id: 37, boardId: 2, title: "Thirty-fifth topic" },
    { id: 38, boardId: 1, title: "Thirty-sixth topic" },
    { id: 39, boardId: 2, title: "Thirty-seventh topic" },
    { id: 40, boardId: 1, title: "Thirty-eighth topic" },
    { id: 41, boardId: 2, title: "Rose" },
    { id: 42, boardId: 1, title: "Lily" },
    { id: 43, boardId: 2, title: "Tulip" },
    { id: 44, boardId: 1, title: "Sunflower" },
    { id: 45, boardId: 2, title: "Daisy" },
    { id: 46, boardId: 1, title: "Orchid" },
    { id: 47, boardId: 2, title: "Carnation" },
    { id: 48, boardId: 1, title: "Hibiscus" },
    { id: 49, boardId: 2, title: "Daffodil" },
    { id: 50, boardId: 1, title: "Peony" },
  ],
  posts: [
    {
      id: 0,
      threadId: 1,
      content: "This is the first post",
      createdAt: 1713731619648,
    },
    {
      id: 1,
      threadId: 1,
      content: "This is the second post",
      createdAt: 1713731619648,
    },
    {
      id: 2,
      threadId: 2,
      content: "This is the third post",
      createdAt: 1713731619648,
    },
    {
      id: 3,
      threadId: 2,
      content: "This is the fourth post",
      createdAt: 1713731619648,
    },
    {
      id: 4,
      threadId: 3,
      content: "This is the fifth post",
      createdAt: 1713731619648,
    },
    {
      id: 5,
      threadId: 3,
      content: "This is the sixth post",
      createdAt: 1713731619648,
    },
    {
      id: 6,
      threadId: 4,
      content: "This is the seventh post",
      createdAt: 1713731619648,
    },
    {
      id: 7,
      threadId: 4,
      content: "This is the eighth post",
      createdAt: 1713731619648,
    },
    {
      id: 8,
      threadId: 5,
      content: "This is the ninth post",
      createdAt: 1713731619648,
    },
    {
      id: 9,
      threadId: 5,
      content: "This is the tenth post",
      createdAt: 1713731619648,
    },
    {
      id: 10,
      threadId: 6,
      content: "This is the eleventh post",
      createdAt: 1713731619648,
    },
    {
      id: 11,
      threadId: 6,
      content: "This is the twelfth post",
      createdAt: 1713731619648,
    },
    {
      id: 12,
      threadId: 7,
      content: "This is the thirteenth post",
      createdAt: 1713731619648,
    },
    {
      id: 13,
      threadId: 7,
      content: "This is the fourteenth post",
      createdAt: 1713731619648,
    },
    {
      id: 14,
      threadId: 8,
      content: "This is the fifteenth post",
      createdAt: 1713731619648,
    },
    {
      id: 15,
      threadId: 8,
      content: "This is the sixteenth post",
      createdAt: 1713731619648,
    },
    {
      id: 16,
      threadId: 9,
      content: "This is the seventeenth post",
      createdAt: 1713731619648,
    },
    {
      id: 17,
      threadId: 9,
      content: "This is the eighteenth post",
      createdAt: 1713731619648,
    },
    {
      id: 18,
      threadId: 10,
      content: "This is the nineteenth post",
      createdAt: 1713731619648,
    },
    {
      id: 19,
      threadId: 10,
      content: "This is the twentieth post",
      createdAt: 1713731619648,
    },
    {
      id: 20,
      threadId: 11,
      content: "This is the twenty-first post",
      createdAt: 1713731619648,
    },
    {
      id: 21,
      threadId: 32,
      content: "Какой ваш любимый фильм последних лет? Обсудим.",
      createdAt: 1701731619648,
    },
    {
      id: 22,
      threadId: 48,
      content: "Как вы проводите выходные? Интересные идеи?",
      createdAt: 1710731619648,
    },
    {
      id: 23,
      threadId: 44,
      content: "Видели последние новости о технологиях? Что думаете?",
      createdAt: 1711731619648,
    },
    {
      id: 24,
      threadId: 4,
      content: "Кто знает хорошие подкасты о науке? Делитесь!",
      createdAt: 1703731619648,
    },
    {
      id: 25,
      threadId: 39,
      content: "Кто поедет на концерт в выходные? Организуем встречу.",
      createdAt: 1713731619648,
    },
    {
      id: 26,
      threadId: 33,
      content: "Какие планы на лето? Путешествия, курсы, хобби?",
      createdAt: 1701731619648,
    },
    {
      id: 27,
      threadId: 35,
      content: "Какие у вас способы борьбы со стрессом? Обсуждаем.",
      createdAt: 1711731619648,
    },
    {
      id: 28,
      threadId: 6,
      content: "Какие сериалы сейчас в тренде? Что порекомендуете?",
      createdAt: 1713731619648,
    },
    {
      id: 29,
      threadId: 37,
      content: "Какие игры вас разочаровали в этом году? Поделитесь мнениями.",
      createdAt: 1713731619648,
    },
    {
      id: 30,
      threadId: 11,
      content: "Ваше мнение о последнем фильме Marvel? Стоит ли смотреть?",
      createdAt: 1703731619648,
    },
    {
      id: 31,
      threadId: 1,
      content: "Какие у вас способы борьбы со стрессом? Обсуждаем.",
      createdAt: 1713731619648,
    },
    {
      id: 32,
      threadId: 23,
      content: "Как вы проводите выходные? Интересные идеи?",
      createdAt: 1713731619648,
    },
    {
      id: 33,
      threadId: 42,
      content: "Какой ваш любимый фильм последних лет? Обсудим.",
      createdAt: 1713731619648,
    },
    {
      id: 34,
      threadId: 48,
      content: "Какие у вас способы борьбы со стрессом? Обсуждаем.",
      createdAt: 1713731619648,
    },
    {
      id: 35,
      threadId: 31,
      content: "Ваше мнение о последнем фильме Marvel? Стоит ли смотреть?",
      createdAt: 1713731619648,
    },
    {
      id: 36,
      threadId: 47,
      content: "Кто знает хорошие подкасты о науке? Делитесь!",
      createdAt: 1702731619648,
    },
    {
      id: 37,
      threadId: 5,
      content: "Какие игры вас разочаровали в этом году? Поделитесь мнениями.",
      createdAt: 1701731619648,
    },
    {
      id: 38,
      threadId: 49,
      content: "Кто в курсе новинок в мире музыки? Что послушать?",
      createdAt: 1713731619648,
    },
    {
      id: 39,
      threadId: 15,
      content: "Какие планы на лето? Путешествия, курсы, хобби?",
      createdAt: 1713731619648,
    },
    {
      id: 40,
      threadId: 14,
      content: "Кто поедет на концерт в выходные? Организуем встречу.",
      createdAt: 1713731619648,
    },
    {
      id: 41,
      threadId: 49,
      content: "Какие у вас способы борьбы со стрессом? Обсуждаем.",
      createdAt: 1713731619648,
    },
    {
      id: 42,
      threadId: 12,
      content: "Ваше мнение о последнем фильме Marvel? Стоит ли смотреть?",
      createdAt: 1713731619648,
    },
    {
      id: 43,
      threadId: 7,
      content: "Какой ваш любимый фильм последних лет? Обсудим.",
      createdAt: 1713731619648,
    },
    {
      id: 44,
      threadId: 10,
      content: "Какие сериалы сейчас в тренде? Что порекомендуете?",
      createdAt: 1713731619648,
    },
    {
      id: 45,
      threadId: 3,
      content: "Какие планы на лето? Путешествия, курсы, хобби?",
      createdAt: 1713731619648,
    },
    {
      id: 46,
      threadId: 22,
      content: "Кто поедет на концерт в выходные? Организуем встречу.",
      createdAt: 1711731619648,
    },
    {
      id: 47,
      threadId: 11,
      content: "Как вы проводите выходные? Интересные идеи?",
      createdAt: 1713731619648,
    },
    {
      id: 48,
      threadId: 19,
      content: "Видели последние новости о технологиях? Что думаете?",
      createdAt: 1713731619648,
    },
    {
      id: 49,
      threadId: 6,
      content: "Кто знает хорошие подкасты о науке? Делитесь!",
      createdAt: 1713731619648,
    },
    {
      id: 50,
      threadId: 5,
      content: "Какие у вас способы борьбы со стрессом? Обсуждаем.",
      createdAt: 1713731619648,
    },
  ],
};
